#!/bin/bash

make -s
echo '=== Make ==='

EXE_PATH='bin/lightang'

runtest(){
    output=$("$EXE_PATH" "$1")
    if [ "$output" != "$2" ]; then
        echo "Exception $1: $output != $2"
        exit 1 
    fi
    echo "$1 => $output"
}

echo "=== Nameric ==="
runtest 0 0
runtest 59 59
runtest '1 2 3' '1
2
3'

echo "=== operators ==="
runtest '+ 1 2' 3
runtest '+ 15 32' 47
runtest '+ 1 + 3 2' 6
runtest '- 10 - 3 2' 9
runtest '* 10 2' 20
runtest '/ 10 2' 5
runtest '+ 2 - 25 * 3 5' 12

echo "=== functions ==="
runtest 'F[+ a a] F(2)' 4
runtest 'F[+ a 2] F(5)' 7
runtest 'F[+ a 4] F(F(F(2)))' 14
runtest 'F[+ a 25] G[F(a)] G(5 10)' 30
runtest 'F[+ a b] F(5 2)' 7
runtest 'F[+ G(1) G(1)] G[+ a a] F()' 4

echo "=== print function ==="
runtest 'PO(+ 1 4)' '5
5'

echo "=== expect test ==="
runtest 'PO(+ 1 4' ''
runtest 'PO + 1 4)' ''
runtest '+ 1 a' ''
#runtest 'F[PO(a) F(b + a b)] F(1 1)' '' // valid. but segmentation falut

echo OK
