#!/bin/bash

make -s
echo '=== Make ==='

EXE_PATH='bin/lightang'

runtest(){
    set -eu
    output=$("$EXE_PATH" "$1")
    if [ "$output" != "$2" ]; then
        echo "Exception: $1 != $2"
        exit 1 
    fi
    echo "$1 => $output"
    echo "==="
}

runtest 0 0
runtest 59 59
runtest '1 2 3' '1
2
3'

echo OK
